services:
  api:
    user: '${UID}:${GID}'
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
      FORCE_COLOR: 1
    networks:
      - invoice

  client:
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    restart: on-failure
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - invoice

  mongodb:
    image: mongo:noble
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - invoice

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    depends_on:
      - mongodb
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
      - invoice

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - invoice

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - pdf_volume:/app/docs
    networks:
      - invoice

networks:
  invoice:
    driver: bridge

volumes:
  mongodb-data:
  static_volume:
  pdf_volume:
